# nginx-deployment.yaml
# Deploys the Nginx web server as a scalable Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: frontend
  labels:
    app: nginx-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx
        image: mysteryman0007/nginx-frontend:latest  # Replace with your image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
