# security-groups.yaml
# Example AWS Security Group rules for Kubernetes cluster nodes

Resources:
  KubernetesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Kubernetes cluster communication
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Restrict to your IP in production
        - IpProtocol: tcp
          FromPort: 6443
          ToPort: 6443
          CidrIp: 0.0.0.0/0  # Kubernetes API server
        - IpProtocol: tcp
          FromPort: 2379
          ToPort: 2380
          CidrIp: 0.0.0.0/0  # etcd server client API
        - IpProtocol: tcp
          FromPort: 10250
          ToPort: 10252
          CidrIp: 0.0.0.0/0  # Kubelet, controller-manager, scheduler
        - IpProtocol: udp
          FromPort: 8472
          ToPort: 8472
          CidrIp: 0.0.0.0/0  # Flannel VXLAN
        - IpProtocol: tcp
          FromPort: 30000
          ToPort: 32767
          CidrIp: 0.0.0.0/0  # NodePort Services
