# flask-service.yaml
# Exposes the Flask API to other services in the cluster
apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: backend
  labels:
    app: flask-api
spec:
  type: ClusterIP
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
