# flask-deployment.yaml
# Deploys the Flask API as a scalable Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: backend
  labels:
    app: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: your-dockerhub-username/flask-api:latest  # Replace with your image
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: FLASK_ENV
        - name: API_FEATURE_FLAG
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: API_FEATURE_FLAG
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: SECRET_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
