# kubeadm-config.yaml
# ClusterConfiguration for kubeadm init
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.28.0
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
controllerManager: {}
scheduler: {}
---
# Add more configuration as needed for your environment
