# mysql-configmap.yaml
# Holds MySQL configuration settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: database
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    max_connections=200
    innodb_buffer_pool_size=128M
